### ISSUE TITLE
Is the project still being maintained?

### ISSUE THREAD

**Issue by renathoaz** [bugst/go-serial#58] opened 2019-02-25 00:28 UTC
I really need some functionalities that @albenik has implemented on his fork. ReadTimeout func. Is this project still alive?

**Comment by cmaglie** [comment] 2019-03-01 13:41
@renathoaz, this library is used on many Arduino projects, we have thousand of users, so I must carefully test every change, especially something like @albenik's fork that touches the core of the library.

For now I'm fully booked on other stuff for the near future, so this won't happen soon.

If @albenik fork is good for your use case, I guess you can just go ahead and use that one.

**Comment by renathoaz** [comment] 2019-03-01 14:13
@cmaglie Thank you for the reply, I got it. I need two little things that I already managed to get, Read Timeout and Custom baud rate for at least windows and linux. I made a fork from Albenik and did it. But I have no time to give maintenance to it. So for while I'll use mine fork until you implement those functionalities. Please refer this issue when you implement it.

**Comment by cbrake** [comment] 2020-05-07 19:27
if you need timeouts, you may want to consider wrapping the serial port with this package:

https://pkg.go.dev/github.com/simpleiot/simpleiot/respreader?tab=doc

I've been using it for modem control (AT commands), and for RS485 protocols like modbus -- seems to be working well.

**Comment by cmaglie** [comment] 2020-05-08 09:32
@cbrake please do not spam the same message over multiple issues, just once is enough, people will find it.

Since this issue is mostly related to timeouts I'm closing it as duplicate of #33

**Closed by cmaglie** 2020-05-08 09:32 UTC
